### ISSUE TITLE
Error during compilling

### ISSUE THREAD

**Issue by dmtrs** [ajfisher/arduino-analog-multiplexer#4]
I get an error during compiling event with blank code like:

     #include <analogmuxdemux.h>

    void setup() {
    }
    void loop() {
    }

    /home/dmtrs/sketchbook/libraries/analogmuxdemux/analogmuxdemux.cpp: In constructor 'AnalogDeMux::AnalogDeMux(uint8_t)':
    /home/dmtrs/sketchbook/libraries/analogmuxdemux/analogmuxdemux.cpp:107:68: error: cannot call constructor 'AnalogDeMux::AnalogDeMux' directly [-fpermissive]
         AnalogDeMux::AnalogDeMux(AMDM_MS0, AMDM_MS1, AMDM_MS2, writepin);
                                                                    ^
    /home/dmtrs/sketchbook/libraries/analogmuxdemux/analogmuxdemux.cpp:107:68: note: for a function-style cast, remove the redundant '::AnalogDeMux'

**Comment by ajfisher** [comment]
Hmmm that's weird.  Not sure why it should be doing that with blank code as
the constructor shouldn't be being called.

If you actually create an instance does it work properly? (Apologies am
away from somewhere I can test this at the moment).

**Comment by dmtrs** [comment]
I have resolved the issue with the code change in the #5 pull request, although I am not using that part at all in my code and I am cpp noob

**Comment by ajfisher** [comment]
Looks good - that form was working fine and it must be something weird going on in compiler with how explicit it is. Oddly the original works under ino so I suspect it's something arduino specific. It's all good though.

Merged.
